theme: minima
title: Hannes Essfors
description: Pre-doctoral researcher at TU Wien working on digital linguistic diversity
homepage: /
nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html
